name: namibia_hockey_union
description: A mobile application for the Namibia Hockey Union to manage teams, events, and players.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mongo_dart: ^0.9.1
  crypto: ^3.0.3
  http: ^1.1.0
  shared_preferences: ^2.2.0
  json_annotation: ^4.8.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true 